name: go_compastravel_${ENV}

services:
  postgres:
    image: postgres:17.2
    container_name: ct-postgres-${ENV}
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ${POSTGRES_VOLUME}:/var/lib/postgresql/data

  backend:
    build:
      context: ../
      dockerfile: docker/backend/Dockerfile
      args:
        ENV: ${ENV}
    container_name: ${BACKEND_CONTAINER_NAME}
    restart: always
    depends_on:
      postgres:
        condition: service_started
    environment:
      DB_DSN: ${POSTGRES_DSN}
      ENV: ${ENV}
    expose:
      - "8080"  # Внутренний порт 8080
    ports: # FIXME удалить порты во вне. Добавить expose
      - "${BACKEND_PORT}:8080"

volumes:
  ct_pg_data_dev:
