INSERT INTO public.permissions (permission_name, description)
VALUES ('admin', 'Административный доступ ко всей системе'),
       ('full', 'Полные права ко всей системе'),
       ('users:full', 'Полные права на пользователей'),
       ('users:create', 'Право на создание пользователей'),
       ('users:view', 'Право на просмотр пользователей'),
       ('users:update', 'Право на обновление пользователей'),
       ('users:delete', 'Право на удаление пользователей'),
       ('users:assign-role', 'Право на назначение ролей'),
       ('users:revoke-role', 'Право на отзыв ролей'),
       ('users:view-roles', 'Право на просмотр ролей'),
       ('users:assign-permission', 'Право на назначение разрешений'),
       ('users:revoke-permission', 'Право на отзыв разрешений'),
       ('users:view-permissions', 'Право на просмотр разрешений'),
       ('roles:full', 'Полные права на роли'),
       ('roles:create', 'Право на создание ролей'),
       ('roles:view', 'Право на просмотр ролей'),
       ('roles:delete', 'Право на удаление ролей'),
       ('permissions:full', 'Полные права на разрешения'),
       ('permissions:create', 'Право на создание разрешений'),
       ('permissions:view', 'Право на просмотр разрешений'),
       ('permissions:delete', 'Право на удаление разрешений');